# Assignment 2


### Task 1: Creating Arrays

In [1]:
import numpy as np

In [5]:
# Create a 1D NumPy array of 10 integers ranging from 1 to 10
arr1 = np.arange(1, 11)
print("1D Array:")
print(arr1)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9. 
arr2 = np.arange(1, 10).reshape(3, 3)
print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3). 
arr3 = np.random.rand(3, 5, 3)
print("3D Array:")
print(arr3)


3D Array:
[[[0.75329686 0.66529489 0.59607138]
  [0.09481682 0.45986723 0.29065623]
  [0.61210722 0.86901732 0.87232176]
  [0.49432127 0.09733915 0.25402976]
  [0.87468519 0.48008868 0.48059556]]

 [[0.89354352 0.94254447 0.31845204]
  [0.39604958 0.64581079 0.97543071]
  [0.83643992 0.035565   0.99243713]
  [0.24949271 0.67051972 0.65639851]
  [0.00099921 0.61338    0.46331243]]

 [[0.63054743 0.44338321 0.92577809]
  [0.50469387 0.07311693 0.36651983]
  [0.42069064 0.21579136 0.28848669]
  [0.4362136  0.94064365 0.08176693]
  [0.85482308 0.47159402 0.21534011]]]


In [8]:
# Display the shape, size, and datatype of each array.

print("1D Array -> Shape:", arr1.shape, ", Size:", arr1.size, ", Dtype:", arr1.dtype)
print("2D Array -> Shape:", arr2.shape, ", Size:", arr2.size, ", Dtype:", arr2.dtype)
print("3D Array -> Shape:", arr3.shape, ", Size:", arr3.size, ", Dtype:", arr3.dtype)

1D Array -> Shape: (10,) , Size: 10 , Dtype: int32
2D Array -> Shape: (3, 3) , Size: 9 , Dtype: int32
3D Array -> Shape: (3, 5, 3) , Size: 45 , Dtype: float64


### Task 2: Array Indexing and Slicing

In [10]:

# 1. Create a NumPy array from the following list:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(data)

print("Original Array:")
print(arr)

# 2. Perform slicing operations

# a) Retrieve the first three elements of the array. 
first_three = arr[:3]
print("First three elements:")
print(first_three)

# b) Retrieve every alternate element of the array.
alternate = arr[::2]
print("Every alternate element:")
print(alternate)

# c) Reverse the array
reversed_arr = arr[::-1]
print("Reversed array:")
print(reversed_arr)

Original Array:
[10 20 30 40 50 60 70 80 90]
First three elements:
[10 20 30]
Every alternate element:
[10 30 50 70 90]
Reversed array:
[90 80 70 60 50 40 30 20 10]


### Task 3: Mathematical Operations 

In [11]:
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("Array A:", A)
print("Array B:", B)

Array A: [13 11 19  3  8]
Array B: [10 20  4  8 16]


In [15]:
add = A + B
print("Addition:", add)

subtract = A - B
print("Subtraction:", subtract)

multiply = A * B
print("Multiplication:", multiply)

divide = A / B
print("Division:", divide)

Addition: [23 31 23 11 24]
Subtraction: [ 3 -9 15 -5 -8]
Multiplication: [130 220  76  24 128]
Division: [1.3   0.55  4.75  0.375 0.5  ]


In [16]:
dot_product = np.dot(A, B)
print("Dot Product:", dot_product)


Dot Product: 578


In [17]:
print("Mean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Standard Deviation of A:", np.std(A))
print("Variance of A:", np.var(A))


Mean of A: 10.8
Median of A: 11.0
Standard Deviation of A: 5.30659966456864
Variance of A: 28.160000000000004


In [19]:
print("Maximum in B:", np.max(B), "Index->",np.argmax(B))
print("Minimum in B:", np.min(B), "Index->",np.argmin(B))

Maximum in B: 20 Index-> 1
Minimum in B: 4 Index-> 2


### Task 4: Reshaping and Transposing

In [20]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
arr_2d = arr.reshape(4, 3)
print("Reshaped to 2D (4,3):")
print(arr_2d)

Reshaped to 2D (4,3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
arr_3d = arr.reshape(2, 2, 3)
print("Reshaped to 3D (2,2,3):")
print(arr_3d)

Reshaped to 3D (2,2,3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
transposed = arr_2d.T
print("Transpose 2D Array:")
print(transposed)
print("Shape of transposed array:", transposed.shape)

Transpose 2D Array:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Shape of transposed array: (3, 4)


### Task 5: Boolean Masking and Filtering 

In [27]:
arr = np.random.randint(10, 51, 15)
print("Original Array:")
print(arr)
print()


greater_than_25 = arr[arr > 25]
print("Elements greater than 25:")
print(greater_than_25)
print()



modified_arr = arr.copy()
modified_arr[modified_arr < 30] = 0
print("Array after replacing elements < 30 with 0:")
print(modified_arr)
print()



count_div_5 = np.sum(arr % 5 == 0)
print("Number of elements divisible by 5:", count_div_5)

Original Array:
[48 41 15 19 24 46 37 17 19 23 11 25 18 28 29]

Elements greater than 25:
[48 41 46 37 28 29]

Array after replacing elements < 30 with 0:
[48 41  0  0  0 46 37  0  0  0  0  0  0  0  0]

Number of elements divisible by 5: 2


### Task 6: Working with Built-in Functions


In [28]:
equally_spaced = np.linspace(0, 1, 10)
print("10 Equally spaced values between 0 and 1:")
print(equally_spaced)

10 Equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [29]:
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:")
print(identity_matrix)



4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
random_array = np.random.randint(1, 101, 20)
sorted_array = np.sort(random_array)
largest_five = sorted_array[-5:]

print("Original Array:")
print(random_array)

print("Sorted Array:")
print(sorted_array)

print("5 Largest Elements:")
print(largest_five)

Original Array:
[55 97 81 97 36 32 98  5 50 17 11 31 55 87 96 49 24 90 34  2]
Sorted Array:
[ 2  5 11 17 24 31 32 34 36 49 50 55 55 81 87 90 96 97 97 98]
5 Largest Elements:
[90 96 97 97 98]


### Task 7: Generic 

In [34]:
import time

A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

print("Arrays A and B generated with shape (100, 100)")

start_time = time.time()
C = np.dot(A, B)
print("Matrix multiplication completed.")

try:
    det = np.linalg.det(C)
    print("Determinant of C:", det)

    if det != 0:
        inv = np.linalg.inv(C)
        print(inv)
        print("Inverse of C calculated successfully.")
    else:
        print("Matrix is singular, inverse not possible.")
except np.linalg.LinAlgError as e:
    print("Error during inversion:", e)


end_time = time.time()
print("Total time taken:", round(end_time - start_time, 4), "seconds")

Arrays A and B generated with shape (100, 100)
Matrix multiplication completed.
Determinant of C: 1.3682936958517573e+50
[[ 16.95607274 -17.90375689 -37.0606352  ... -34.72899496   2.18960418
  -45.01582444]
 [ -9.57110318   9.84493362  20.33324428 ...  20.29558284  -0.70781895
   25.75686759]
 [ -1.1614071    1.55701678   2.20796132 ...   3.36897946  -0.40767613
    3.24295325]
 ...
 [ -4.38934906   4.06733028   9.09932865 ...   8.08462173  -0.24361599
   11.231307  ]
 [ -0.49249701   0.54777933   1.02922871 ...   1.12340593  -0.26314322
    1.43463089]
 [ 10.6392869   -9.77081203 -21.87476139 ... -20.97533152   0.33069149
  -27.75665408]]
Inverse of C calculated successfully.
Total time taken: 0.0614 seconds
